/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

//Librerías variables

#include <stdint.h>

//Librerías para tipos de variables booleanas
#include <stdbool.h>

//Librería para operaciones matemáticas
#include <math.h>

#define NOP() __asm("NOP")


void miPrimeraFuncion(void); //La función no entrega ni recibe nada

uint8_t getMaxChar(void);

int main (void){


	miPrimeraFuncion();

	while(1){

		miPrimeraFuncion();
	}
}

 void miPrimeraFuncion (void){

	 //Manejo de variable booleanas

	 uint8_t miPrimeraBandera = true;
	 uint8_t miSegundaBandera = false;

	 uint8_t XOR = miPrimeraBandera ^ miSegundaBandera;
	 uint8_t OR = miPrimeraBandera || miSegundaBandera;
	 uint8_t AND =miPrimeraBandera && miSegundaBandera;

	 XOR^=1;
	 XOR^=1;

 }

