/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

//Librerías variables

#include <stdint.h>


//1.0 Paso por valor básico

void duplicarNumero (uint8_t numero){
	numero *= 2;
}

//1.1 Paso por referencia

void duplicarNumeroRef (uint8_t *numero){
	*numero = (*numero)* 2;
}
int main(void){

	uint8_t n=10;

	//Pasamos por valor

	duplicarNumero(n);

	uint8_t m=20;

	//Pasamos por referencia

	duplicarNumeroRef(&m);

	//Reaignamos valores

	n=6;

	m = 14;

}
